import {changeTitle} from './utils/changeTitle';
import {restoreFilterSettings, initializeFilters} from './utils/filters';
import {resistanceTab} from './utils/resistanceTab';
import {replaceChecker} from './utils/replaceChecker';
import {cssBg} from './utils/cssBg';
import {canvasBg} from './utils/canvasBg';
import {fakeFPS} from './utils/fakeFPS';
import {gmOverride} from './utils/gmOverride';
import {initObserver} from './utils/initObserver';

changeTitle('BlurStyle');
restoreFilterSettings();
initializeFilters();
resistanceTab();
replaceChecker();
cssBg();
canvasBg();
fakeFPS();
gmOverride();
initObserver();